version: '2'
services:
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=reviewboard
            - POSTGRES_PASSWORD=reviewboard
    memcached:
        image: memcached:alpine
    reviewboard:
        build: ./
        restart: always
        volumes:
            - /var/www/
        depends_on:
            - postgres
            - memcached
        environment:
            - PGHOST=postgres
            - PGPASSWORD=reviewboard
            - MEMCACHED=memcached:11211
            - WAIT_FOR_POSTGRES=true
        ports:
            - 8000:8000
